### ISSUE TITLE
クォート(ダブルクォーテーション/シングルクォーテーション)で囲まれてる列を扱えるオプションの追加

### ISSUE THREAD

**Issue by blacknon** [xztaityozx/sel#34]
## 概要

Excelとかでcsvにエクスポートすると↓みたいなcsvが生成されるんですが、これらに対して列を正常に指定できるオプションがあると嬉しい…かも？と思いました。

```csv
0,てきすと,すうじ
1,うん○っこっこ〜の子元気の子,200
2,"Oh, It's Big Poop...",240
3,テキストがひどかったかも…？,"100,000"
4,そんなこ\"とないか,"114,114"
```

**Comment by xztaityozx** [comment]
CSVたしかに〜って思いました。サッと実装してみます。

ちなみに自分はいつも
[csvq](https://github.com/mithrandie/csvq)を使ってました。
